[project]
name = "birdnet-v3-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jeff Matheson", email = "jeff.matheson@tetratech.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "streamlit>=1.63.0",
]

[project.scripts]
birdnet-v3-project = "birdnet_v3_project:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
